import 'package:get/get_navigation/src/root/internacionalization.dart';

class Langaugae extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "email": "Email",
          "name": "Name",
          "mobile": "mobile",
          "password": "Password",
          "forgetPassword": "Forgot Password",
          "confirmPassword": "Confirm Password",
          "signUp": "Sign Up",
          "login": "Log In",
          "signIn": "Sign in",
          "welcomeBack": "Hello! \nWELCOME BACK",
          "alreadyAccount": "Already have account ?",
          "makeHomeBeautiful": "MAKE HOME \nBEAUTIFUL",
          "favourite": "Favourite",
          "addAllMyCart": "Add all to my cart",
          "notificationScreen": "NotificationScreen",
          "profile": "Profile",
          "myOrder": "My orders",
          "alreadyOrder": "Already have 10 orders",
          "shipAddress": "Shipping Addresses",
          "addShipAddress": "Add Shipping Address",
          "getAddress": "03 Addresses",
          "paymentMethod": "Payment Method",
          "deliveryMethod": "Delivery method",
          "payment": "Payment",
          "delivery": "delivery",
          "haveCard": "You have 2 cards",
          "myReviews": "My  reviews",
          "reviewItem": "Reviews for 5 items",
          "setting": "Setting",
          "faqDesc": "Notification, Password, FAQ, Contact",
          "myCart": "my cart",
          "order": "Order",
          "total": "Total",
          "2day": "2 days",
          "checkOut": "Check Out",
          "submitOrder": "Submit order",
          "addToCart": "Add to Cart",
          "success": "SUCCESS!",
          "trackYourOrder": "Track your orders",
          "backHome": "Back to home",
          "orderNo": "order no",
          "date": "date",
          "detail": "Detail",
          "totalAmount": "Total Amount",
          "quantity": "Quantity",
          "cancel": "Cancel",
          "saveAddress": "Save Address",
          "country": "Country",
          "city": "City",
          "district": "District",
          "code": "Zip code",
          "address": "Address",
          "personalInfo": "Personal information",
          "rating": "Rating & Review",
          "writeRev": "Write a review",
          "helpCenter": "Help Center",
          "fAQ": "FAQ",
          "language": "Language",
          "privacy": "Privacy & Terms",
          "logOut": "Log out",
          "contactUs": "Contact Us",
          "welcome": "WELCOME",
          "orderComing":
              "Your order will be delivered soon. \nThank you for choosing our app!",
        },
        "gu_IN": {"email": "ઇમેઇલ"}
      };
}
