import 'package:get/get_navigation/src/root/internacionalization.dart';

class Langaugae extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "email": "Email",
          "name": "Name",
          "mobile": "mobile",
          "password": "Password",
          "forgetPassword": "Forgot Password",
          "confirmPassword": "Confirm Password",
          "signUp": "Sign Up",
          "login": "Log In",
          "signIn": "Sign in",
          "welcomeBack": "Hello! \nWELCOME BACK",
          "alreadyAccount": "Already have account ?",
          "makeHomeBeautiful": "MAKE HOME \nBEAUTIFUL",
          "favourite": "Favourite",
          "addAllMyCart": "Add all to my cart",
          "notificationScreen": "NotificationScreen",
          "profile": "Profile",
          "myOrder": "My orders",
          "alreadyOrder": "Already have 10 orders",
          "shipAddress": "Shipping Addresses",
          "addShipAddress": "Add Shipping Address",
          "getAddress": "03 Addresses",
          "paymentMethod": "Payment Method",
          "deliveryMethod": "Delivery method",
          "payment": "Payment",
          "delivery": "delivery",
          "haveCard": "You have 2 cards",
          "myReviews": "My  reviews",
          "reviewItem": "Reviews for 5 items",
          "setting": "Setting",
          "faqDesc": "Notification, Password, FAQ, Contact",
          "myCart": "my cart",
          "order": "Order",
          "total": "Total",
          "2day": "2 days",
          "checkOut": "Check Out",
          "submitOrder": "Submit order",
          "addToCart": "Add to Cart",
          "success": "SUCCESS!",
          "trackYourOrder": "Track your orders",
          "backHome": "Back to home",
          "orderNo": "order number",
          "date": "date",
          "detail": "Detail",
          "totalAmount": "Total Amount",
          "quantity": "Quantity",
          "cancel": "Cancel",
          "saveAddress": "Save Address",
          "country": "Country",
          "city": "City",
          "district": "District",
          "code": "Zip code",
          "address": "Address",
          "personalInfo": "Personal information",
          "rating": "Rating & Review",
          "writeRev": "Write a review",
          "helpCenter": "Help Center",
          "fAQ": "FAQ",
          "language": "Language",
          "privacy": "Privacy & Terms",
          "logOut": "Log out",
          "contactUs": "Contact Us",
          "welcome": "WELCOME",
          "orderComing":
              "Your order will be delivered soon. \nThank you for choosing our app!",
        },
        "gu_IN": {
          "email": "ઇમેઇલ",
          "name": "નામ",
          "mobile": "મોબાઇલ",
          "password": "પાસવર્ડ",
          "forgetPassword": "પાસવર્ડ ભૂલી ગયા છો",
          "confirmPassword": "પાસવર્ડની પુષ્ટિ કરો",
          "signUp": "સાઇન અપ કરો",
          "login": "પ્રવેશ કરો",
          "signIn": "સાઇન ઇન કરો",
          "welcomeBack": "નમસ્તે! \nઆપનું સ્વાગત છે",
          "alreadyAccount": "પહેલેથી એકાઉન્ટ છે ?",
          "makeHomeBeautiful": "ઘરને \nસુંદર બનાવો",
          "favourite": "મનપસંદ",
          "addAllMyCart": "મારા કાર્ટમાં બધું ઉમેરો",
          "notificationScreen": "સૂચના સ્ક્રીન",
          "profile": "પ્રોફાઇલ",
          "myOrder": "મારા ઓર્ડર",
          "alreadyOrder": "પહેલેથી જ 10 ઓર્ડર છે",
          "shipAddress": "શિપિંગ સરનામાં",
          "addShipAddress": "શિપિંગ સરનામું ઉમેરો",
          "getAddress": "03 સરનામાં",
          "paymentMethod": "ચુકવણી પદ્ધતિ",
          "deliveryMethod": "વિતરણની પદ્ધતિ",
          "payment": "ચુકવણી",
          "delivery": "વિતરણ",
          "haveCard": "તમારી પાસે 2 કાર્ડ છે",
          "myReviews": "મારી સમીક્ષાઓ",
          "reviewItem": "5 વસ્તુઓ માટે સમીક્ષાઓ",
          "setting": "સેટિંગ",
          "faqDesc": "સૂચના, પાસવર્ડ, FAQ, સંપર્ક",
          "myCart": "મારી કાર્ટ",
          "order": "ઓર્ડર",
          "total": "કુલ",
          "2day": "2 દિવસ",
          "checkOut": "તપાસો",
          "submitOrder": "ઓર્ડર સબમિટ કરો",
          "addToCart": "સૂચી માં સામેલ કરો",
          "success": "સફળતા!",
          "trackYourOrder": "તમારા ઓર્ડરને ટ્રૅક કરો",
          "backHome": "ઘરે પાછા",
          "orderNo": "ઓર્ડર નંબરો",
          "date": "તારીખ",
          "detail": "વિગત",
          "totalAmount": "કુલ રકમ",
          "quantity": "જથ્થો",
          "cancel": "રદ કરો",
          "saveAddress": "સરનામું સાચવો",
          "country": "દેશ",
          "city": "શહેર",
          "district": "જિલ્લો",
          "code": "પિન કોડ",
          "address": "સરનામું",
          "personalInfo": "વ્યક્તિગત માહિતી",
          "rating": "રેટિંગ અને સમીક્ષા",
          "writeRev": "એક સમીક્ષા લખો",
          "helpCenter": "મદદ કેન્દ્ર",
          "fAQ": "FAQ",
          "language": "ભાષા",
          "privacy": "ગોપનીયતા અને શરતો",
          "logOut": "લૉગ આઉટ",
          "contactUs": "અમારો સંપર્ક કરો",
          "welcome": "સ્વાગત છે",
          "orderComing":
              "તમારો ઓર્ડર ટૂંક સમયમાં વિતરિત કરવામાં આવશે. \nઅમારી એપ્લિકેશન પસંદ કરવા બદલ આભાર!",
        },
        "hi_IN": {
          "email": "ईमेल",
          "name": "नाम",
          "mobile": "मोबाइल",
          "password": "पासवर्ड",
          "forgetPassword": "पासवर्ड भूल गए",
          "confirmPassword": "पासवर्ड की पुष्टि कीजिये",
          "signUp": "साइन अप करें",
          "login": "लॉग इन करें",
          "signIn": "दाखिल करना",
          "welcomeBack": "नमस्ते! \nवापसी पर स्वागत है",
          "alreadyAccount": "पहले से खाता है ?",
          "makeHomeBeautiful": "घर को \nसुंदर बनाएं",
          "favourite": "प्रिय",
          "addAllMyCart": "मेरे कार्ट में सभी जोड़ें",
          "notificationScreen": "अधिसूचना स्क्रीन",
          "profile": "प्रोफ़ाइल",
          "myOrder": "मेरे आदेश",
          "alreadyOrder": "पहले से ही 10 ऑर्डर हैं",
          "shipAddress": "भेजने का पता",
          "addShipAddress": "शिपिंग पता जोड़ें",
          "getAddress": "03 पते",
          "paymentMethod": "भुगतान विधि",
          "deliveryMethod": "डिलिवरी विधि",
          "payment": "भुगतान",
          "delivery": "वितरण",
          "haveCard": "आपके पास 2 कार्ड हैं",
          "myReviews": "मेरी समीक्षाएं",
          "reviewItem": "5 आइटम के लिए समीक्षाएँ",
          "setting": "सेटिंग",
          "faqDesc": "अधिसूचना, पासवर्ड, अक्सर पूछे जाने वाले प्रश्न, संपर्क",
          "myCart": "मेरा कार्ट",
          "order": "आदेश",
          "total": "कुल",
          "2day": "दो दिन",
          "checkOut": "चेक आउट",
          "submitOrder": "आदेश प्रस्तुत",
          "addToCart": "कार्ट में जोड़ें",
          "success": "सफलता!",
          "trackYourOrder": "अपने आदेश ट्रैक करें",
          "backHome": "घर वापिस जा रहा हूँ",
          "orderNo": "क्रम संख्या",
          "date": "तारीख",
          "detail": "विवरण",
          "totalAmount": "कुल राशि",
          "quantity": "मात्रा",
          "cancel": "रद्द करना",
          "saveAddress": "पता सहेजें",
          "country": "देश",
          "city": "शहर",
          "district": "ज़िला",
          "code": "ज़िप कोड",
          "address": "पता",
          "personalInfo": "व्यक्तिगत जानकारी",
          "rating": "रेटिंग और समीक्षा",
          "writeRev": "एक समीक्षा लिखे",
          "helpCenter": "सहायता केंद्र",
          "fAQ": "सामान्य प्रश्न",
          "language": "भाषा",
          "privacy": "गोपनीयता व शर्तें",
          "logOut": "लॉग आउट",
          "contactUs": "संपर्क करें",
          "welcome": "स्वागत",
          "orderComing": "आपका ऑर्डर जल्द ही डिलीवर कर दिया जाएगा। \nहमारे ऐप को चुनने के लिए धन्यवाद!",
        },
      };
}
